[Core]
  Remote = false
  [Core.RemoteConfig]
    Protocol = "tcp"
    RemoteAddr = "192.167.10.0:26657"

[P2P]
  ListenAddresses = ["/ip4/0.0.0.0/tcp/2121", "/ip6/::/tcp/2121"]
  AnnounceAddresses = []
  NoAnnounceAddresses = ["/ip4/0.0.0.0/tcp/2121", "/ip4/127.0.0.1/tcp/2121", "/ip6/::/tcp/2121"]
  Network = "ephemeral"
  Bootstrapper = false
  BootstrapPeers = []
  MutualPeers = []
  PeerExchange = false
  [P2P.ConnManager]
    Low = 50
    High = 100
    GracePeriod = 60000000000

[RPC]
  ListenAddr = ""
